### PR TITLE
Add check_controller_update() and check_firmware_update() methods

### PR DESCRIPTION
**Pull request by brenard**
I'm add possibility to check for controller and device firmwares updates. This information is cached by the controller.

Implement and test and the latest Unifi controller version _(6.0.28)_.

### CODE REVIEW

**Comment by malle-pietje** [comment]
Thanks, will have a closer look. Which firmware check is actually triggered with the second function/method? That of the UniFi devices or of the controller host (CloudKey, UDM, UDM PRO)?

**Comment by brenard** [comment]
> Thanks, will have a closer look. Which firmware check is actually triggered with the second function/method? That of the UniFi devices or of the controller host (CloudKey, UDM, UDM PRO)?

I think it's the Unifi device firmwares: in Unifi controller interface, it's correspond to _Device Firmware Updates_ in _Settings > System settings > Maintenance > Update_.

**Comment by malle-pietje** [comment]
OK, thanks' I'll merge this in with the next release.

**Comment by malle-pietje** [comment]
Merged with release v1.1.59. Thanks for your contribution!

**Pull request closed without merging**
