### PR TITLE
Add a few more function for setting site specific parameters. It was …

### PR DESCRIPTION
**Pull request by smos**
…neccesary to create several setting functions

for setting the information, although the site configuration is returned whole as one object.

I also added a provisioning example that I use with our internal ERP that automatically creates, updates and deletes sites according to internal ERP
site information. I added a settings template that has a couple of the most useful defaults, like auto upgrade, country and locale.

### CODE REVIEW

**Comment by malle-pietje** [comment]
Thanks for the submission. I had actually started preparations for an update including these site-related routes so you beat me to it:wink:

I'll go through the methods and the example (which looks very useful) before I merge this in.

**Comment by malle-pietje** [comment]
Thanks, merged. I may change the example a bit and give it it’s own directory and README due to to number of files it contains.

**Comment by smos** [comment]
I have some more fixes for the provisioning script that actually compares settings to configured settings so it only triggers for actual updates. Also, I made it automatically adopt devices if it matches a shop network. I can upload those changes on monday. I'll send the separately

**Comment by malle-pietje** [comment]
Perfect, thanks!

**Pull request merged**
