### PR TITLE
Dev edit client fixedip

### PR DESCRIPTION
**Pull request by Warafux**
Fixed some errors/misunderstandings of the last PR 
https://github.com/Art-of-WiFi/UniFi-API-client/pull/23

Also added optional parameter to get specific network data by its ID

### CODE REVIEW

**Comment by malle-pietje** [comment]
Thanks, let me check the PR before I pull it into the repo.

**Comment by Warafux** [comment]
By the way, if noticed that if you try to fix an already fixed ip, nothing changes and an empty array is returned.
Also, if there's any ip fixed, it will only apply if the device is connected to that network. For example, if I'm connected to network_1 and then configure an ip fixed to network_2, after reconnecting the device to network_1 automatic dhcp will be applied (ignoring network/ip fixing). If I connect the same device to network_2, the dhcp rule will apply and the device will get the previously fixed ip.
It's a bit tricky imo.

Thank you again!

**Comment by malle-pietje** [comment]
Yes, it would be nice if you could assign a fixed IP address per network. Maybe something for a future controller release?;-)

**Comment by Warafux** [comment]
@malle-pietje  Hey mate, how's that PR check? 😆

**Comment by malle-pietje** [comment]
Very busy at the moment, will see whether I can do this over the weekend. I prefer to do this thoroughly since quite a lot of projects (I am guessing 3K+...) are relying on this class ATM.

**Comment by Warafux** [comment]
Sure! Let me know if there's something I've to fix/review

**Comment by malle-pietje** [comment]
Merged, apologies for the delay...

**Pull request merged**
