### PR TITLE
Added adoption failed state and advanced adoption

### PR DESCRIPTION
**Pull request by Sarrus**
Hi there,

A very minor one, I've added 'adoption failed' to the known states. Tested against a CloudKey running 6.1.71

Thanks,

### CODE REVIEW

**Comment by malle-pietje** [comment]
Excellent, thanks for the PR. Will merge this in with the next update!

**Comment by Sarrus** [comment]
Hi Again,

I've added a second commit which adds a function to adopt with custom SSH credentials.

Thanks,

**Comment by malle-pietje** [comment]
That's cool, thanks.

**Comment by malle-pietje** [comment]
Manually merged in with 1.1.71

**Pull request closed without merging**
